/*MARK DOWN for DATABASE*/


USE [C:\USERS\ROCHELLE SIMPSON\DOCUMENTS\CS460\HW8\HW8\APP_DATA\ARTGALLERYDB.MDF];  
DROP TABLE IF EXISTS dbo.ARTISTS;
DROP TABLE IF EXISTS dbo.GENRES;
DROP TABLE IF EXISTS dbo.ARTWORKS;
DROP TABLE IF EXISTS dbo.CLASSIFICATIONS ;

GO