/*MARK DOWN for DATABASE*/


USE [C:\USERS\ROCHELLE SIMPSON\DOCUMENTS\CS460\HW8\HW8\APP_DATA\ARTGALLERYDB.MDF];  
GO  
ALTER TABLE Artwork
DROP CONSTRAINT ArtistID
DROP TABLE Artwork

ALTER TABLE Genre
DROP CONSTRAINT ArtworkID
DROP TABLE  Genre;

ALTER TABLE Classification
DROP CONSTRAINT ArtworkID, GenreID
DROP TABLE  Classification;

DROP TABLE Artist;

	